[project]
name="gravity_simulation"
version="1.0.0"
description="A package to create simple 2D gravity simulations"
readme = "README.md"
requires-python = ">=3.12"
dependencies = []

[project.scripts]
simulation = "src.gravity_simulation.__main__.main"